version: "3.8"

services:
  webhook:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "30017:30017"
    environment:
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
    volumes:
      - ./credentials.json:/app/credentials.json:ro
    restart: unless-stopped