name: Python Build & Deploy

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  deploy:
    name: Build & Deploy to Server
    runs-on: ubuntu-latest

    steps:
      - name: "Deploy via SSH"
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 60022
          script: |
            cd ~/planning
            git pull origin main
            docker compose down
            docker compose build
            docker compose up -d
