name: Python build

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  upload-container:
    name: Build & upload container to GHCR
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: youmni
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/integrationproject1/planning:latest


  deploy:
    name: Deploy to server
    runs-on: ubuntu-latest
    needs: upload-container

    steps:
      - name: "Deploy"
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 60022
          script: |
            cd ~/planning
            docker compose pull
            docker compose up -d