name: Integration Tests

on:
  push:
    branches: [ features_youmni ]
  pull_request:
    branches: [ features_youmni ]

jobs:
  build:
    name: Build & Test Planning App
    runs-on: ubuntu-latest

    env:
      MYSQL_ROOT_PASSWORD: test_root_pw
      MYSQL_DATABASE: test_db
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_pw
      MYSQL_HOST: mysql

      RABBITMQ_HOST: localhost
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: guest
      RABBITMQ_PASSWORD: guest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest-order

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker images
        run: docker compose -f docker-compose.yml build

      - name: Start Docker containers
        run: docker compose -f docker-compose.yml up -d

      - name: Wait for MySQL
        run: |
          for i in {1..30}; do
            docker exec $(docker ps -qf name=mysql) mysqladmin ping -h "localhost" -u"$MYSQL_USER" -p"$MYSQL_PASSWORD" --silent && echo "✅ MySQL ready" && break
            sleep 2
          done

      - name: Wait for RabbitMQ
        run: |
          for i in {1..30}; do
            curl -u guest:guest http://localhost:30021/api/overview && echo "✅ RabbitMQ ready" && break
            sleep 2
          done || echo "RabbitMQ not responding"

      - name: Wait for Flask API (session_producer)
        run: |
          for i in {1..30}; do
            curl -s http://localhost:30015/api/calendar-ping && echo "✅ Flask API ready" && break
            sleep 2
          done

      - name: Run tests
        run: pytest tests/integration --tb=short -v

      - name: Show logs and stop containers
        if: always()
        run: |
          docker compose -f docker-compose.yml logs
          docker compose -f docker-compose.yml down
