name: CI

on:
  push:
    branches:
      - features_youmni
  pull_request:
    branches:
      - features_youmni

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:20.10.24-dind
        options: --privileged

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Set up Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.24.5/docker-compose-linux-x86_64" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Create .env file
        run: |
          echo "MYSQL_ROOT_PASSWORD=test_root_pw" >> .env
          echo "MYSQL_DATABASE=test_db" >> .env
          echo "MYSQL_USER=test_user" >> .env
          echo "MYSQL_PASSWORD=test_pw" >> .env
          echo "MYSQL_HOST=mysql" >> .env
          echo "RABBITMQ_HOST=rabbitmq" >> .env
          echo "RABBITMQ_PORT=5672" >> .env
          echo "RABBITMQ_USER=guest" >> .env
          echo "RABBITMQ_PASSWORD=guest" >> .env

      - name: Build and start containers
        run: |
          docker-compose -f docker-compose.ci.yml up -d --build

      - name: Wait for services to be ready
        run: |
          echo "Wachten op RabbitMQ en MySQL om klaar te zijn..."
          sleep 20

      - name: Run unit tests
        run: |
          docker-compose -f docker-compose.ci.yml exec -T event_producer pytest -v

      - name: Show container logs on failure
        if: failure()
        run: docker-compose -f docker-compose.ci.yml logs

      - name: Stop containers
        run: docker-compose -f docker-compose.ci.yml down
